-- Runtime projections used by the existing Trosa HTTP/API code.
--
-- These objects live in the same PostgreSQL database and point at the
-- normalized core/trosa/audit tables.  They are a compatibility surface for
-- the current API vocabulary; they are not a second database or a sync job.

BEGIN;

CREATE TABLE IF NOT EXISTS trosa.account_legacy_refs (
    organization_id uuid NOT NULL REFERENCES identity.organizations(id),
    legacy_user_id text NOT NULL,
    legacy_customer_id bigint NOT NULL,
    account_id uuid NOT NULL REFERENCES trosa.accounts(id),
    source_db text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (organization_id, legacy_user_id, legacy_customer_id),
    UNIQUE (organization_id, source_db, legacy_customer_id)
);

CREATE INDEX IF NOT EXISTS trosa_account_legacy_refs_account_idx
    ON trosa.account_legacy_refs (account_id, legacy_user_id);

CREATE TABLE IF NOT EXISTS trosa.legacy_row_refs (
    organization_id uuid NOT NULL REFERENCES identity.organizations(id),
    legacy_user_id text NOT NULL,
    table_name text NOT NULL,
    legacy_id bigint NOT NULL,
    target_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (organization_id, legacy_user_id, table_name, legacy_id)
);

CREATE INDEX IF NOT EXISTS trosa_legacy_row_refs_target_idx
    ON trosa.legacy_row_refs (target_id, table_name);

CREATE TABLE IF NOT EXISTS trosa.contact_legacy_refs (
    organization_id uuid NOT NULL REFERENCES identity.organizations(id),
    legacy_user_id text NOT NULL,
    legacy_contact_id bigint NOT NULL,
    legacy_customer_id bigint NOT NULL,
    account_id uuid NOT NULL REFERENCES trosa.accounts(id),
    person_id uuid REFERENCES core.people(id),
    contact_method_id uuid REFERENCES core.contact_methods(id),
    name text NOT NULL DEFAULT '',
    title text NOT NULL DEFAULT '',
    phone text NOT NULL DEFAULT '',
    whatsapp text NOT NULL DEFAULT '',
    linkedin text NOT NULL DEFAULT '',
    preferred_channel text NOT NULL DEFAULT '',
    contact_type text NOT NULL DEFAULT 'person',
    is_primary boolean NOT NULL DEFAULT false,
    notes text NOT NULL DEFAULT '',
    legacy_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (organization_id, legacy_user_id, legacy_contact_id)
);

CREATE INDEX IF NOT EXISTS trosa_contact_legacy_refs_customer_idx
    ON trosa.contact_legacy_refs (organization_id, legacy_user_id, legacy_customer_id, is_primary DESC);

CREATE TABLE IF NOT EXISTS trosa.weekly_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES identity.organizations(id),
    legacy_user_id text NOT NULL,
    week_start text NOT NULL,
    content text NOT NULL DEFAULT '',
    highlights text NOT NULL DEFAULT '',
    challenges text NOT NULL DEFAULT '',
    next_plan text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'draft',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organization_id, legacy_user_id, week_start)
);

CREATE TABLE IF NOT EXISTS identity.team_invitations (
    id text PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES identity.organizations(id),
    token_hash text NOT NULL UNIQUE,
    created_by text NOT NULL,
    created_at text NOT NULL,
    expires_at text NOT NULL,
    accepted_at text NOT NULL DEFAULT '',
    accepted_user_id text NOT NULL DEFAULT '',
    revoked_at text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS trosa.email_verifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES identity.organizations(id),
    legacy_user_id text NOT NULL,
    email text NOT NULL,
    normalized_email text NOT NULL,
    domain text NOT NULL DEFAULT '',
    deliverability_status text NOT NULL DEFAULT 'unknown',
    confidence text NOT NULL DEFAULT 'low',
    address_type text NOT NULL DEFAULT 'person',
    risk_flags jsonb NOT NULL DEFAULT '[]'::jsonb,
    evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
    mx_records jsonb NOT NULL DEFAULT '[]'::jsonb,
    checked_at text NOT NULL DEFAULT '',
    expires_at text NOT NULL DEFAULT '',
    UNIQUE (organization_id, legacy_user_id, normalized_email)
);

CREATE TABLE IF NOT EXISTS trosa.email_verification_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES identity.organizations(id),
    legacy_user_id text NOT NULL,
    email text NOT NULL,
    domain text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'queued',
    attempts integer NOT NULL DEFAULT 0,
    next_run_at text NOT NULL DEFAULT '',
    last_error text NOT NULL DEFAULT '',
    created_at text NOT NULL DEFAULT '',
    updated_at text NOT NULL DEFAULT '',
    UNIQUE (organization_id, legacy_user_id, email)
);

CREATE TABLE IF NOT EXISTS trosa.email_domain_probes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES identity.organizations(id),
    legacy_user_id text NOT NULL,
    domain text NOT NULL,
    catchall_status text NOT NULL DEFAULT 'unknown',
    evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
    checked_at text NOT NULL DEFAULT '',
    next_check_at text NOT NULL DEFAULT '',
    UNIQUE (organization_id, legacy_user_id, domain)
);

CREATE TABLE IF NOT EXISTS trosa.email_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES identity.organizations(id),
    legacy_user_id text NOT NULL,
    status text NOT NULL,
    message text NOT NULL DEFAULT '',
    reminder_count integer NOT NULL DEFAULT 0,
    created_at text NOT NULL DEFAULT ''
);

-- The source SQLite ledgers use a per-user integer id.  PostgreSQL's
-- generated id remains the physical identity, while these legacy keys make
-- repeated imports and user-scoped API projections deterministic.
ALTER TABLE trosa.email_verifications ADD COLUMN IF NOT EXISTS legacy_id bigint;
ALTER TABLE trosa.email_verification_jobs ADD COLUMN IF NOT EXISTS legacy_id bigint;
ALTER TABLE trosa.email_domain_probes ADD COLUMN IF NOT EXISTS legacy_id bigint;
ALTER TABLE trosa.email_logs ADD COLUMN IF NOT EXISTS legacy_key text NOT NULL DEFAULT '';
CREATE UNIQUE INDEX IF NOT EXISTS trosa_email_verification_legacy_idx
    ON trosa.email_verifications (organization_id, legacy_user_id, legacy_id)
    WHERE legacy_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS trosa_email_verification_job_legacy_idx
    ON trosa.email_verification_jobs (organization_id, legacy_user_id, legacy_id)
    WHERE legacy_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS trosa_email_domain_probe_legacy_idx
    ON trosa.email_domain_probes (organization_id, legacy_user_id, legacy_id)
    WHERE legacy_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS trosa_email_logs_legacy_key_idx
    ON trosa.email_logs (organization_id, legacy_user_id, legacy_key)
    WHERE legacy_key <> '';

CREATE TABLE IF NOT EXISTS audit.agent_gateway_idempotency (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES identity.organizations(id),
    legacy_user_id text NOT NULL,
    action text NOT NULL,
    idempotency_key text NOT NULL,
    request_sha256 text NOT NULL,
    proposal_id uuid,
    response_json jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organization_id, legacy_user_id, action, idempotency_key)
);

CREATE TABLE IF NOT EXISTS audit.imported_activity_rows (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES identity.organizations(id),
    legacy_user_id text NOT NULL,
    activity_hash text NOT NULL,
    source_key text NOT NULL DEFAULT '',
    batch_id uuid REFERENCES audit.import_batches(id) ON DELETE SET NULL,
    account_id uuid REFERENCES trosa.accounts(id) ON DELETE CASCADE,
    source_name text NOT NULL,
    source_sheet text NOT NULL DEFAULT '',
    source_cell text NOT NULL DEFAULT '',
    source_header text NOT NULL DEFAULT '',
    activity_id uuid,
    imported_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organization_id, activity_hash)
);

CREATE TABLE IF NOT EXISTS audit.import_unmatched_customers (
    id uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES identity.organizations(id),
    legacy_user_id text NOT NULL,
    unmatched_hash text NOT NULL DEFAULT '',
    batch_id uuid REFERENCES audit.import_batches(id) ON DELETE CASCADE,
    customer_name text NOT NULL,
    country text NOT NULL DEFAULT '',
    website text NOT NULL DEFAULT '',
    source_sheet text NOT NULL DEFAULT '',
    source_row integer,
    reason text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organization_id, unmatched_hash)
);

CREATE OR REPLACE FUNCTION trosa.compat_current_user() RETURNS text
LANGUAGE sql STABLE AS $$
    SELECT COALESCE(NULLIF(current_setting('trade_os.user', true), ''), 'hamid')
$$;

CREATE OR REPLACE FUNCTION trosa.compat_normalized_name(value text) RETURNS text
LANGUAGE sql IMMUTABLE AS $$
    SELECT trim(regexp_replace(regexp_replace(lower(coalesce(value, '')), '[^a-z0-9]+', ' ', 'g'), '\s+', ' ', 'g'))
$$;

CREATE OR REPLACE FUNCTION trosa.compat_domain(value text) RETURNS text
LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE
    result text := lower(trim(coalesce(value, '')));
BEGIN
    IF result = '' THEN RETURN ''; END IF;
    result := regexp_replace(result, '^https?://', '');
    result := split_part(result, '/', 1);
    result := split_part(result, '@', 2);
    result := split_part(result, ':', 1);
    RETURN regexp_replace(result, '^www\.', '');
END
$$;

CREATE OR REPLACE FUNCTION trosa.compat_uuid(seed text) RETURNS uuid
LANGUAGE sql IMMUTABLE AS $$
    SELECT (substr(md5(coalesce(seed, '')), 1, 8) || '-' ||
            substr(md5(coalesce(seed, '')), 9, 4) || '-' ||
            substr(md5(coalesce(seed, '')), 13, 4) || '-' ||
            substr(md5(coalesce(seed, '')), 17, 4) || '-' ||
            substr(md5(coalesce(seed, '')), 21, 12))::uuid
$$;

CREATE OR REPLACE VIEW trosa.users AS
SELECT u.legacy_user_id AS id,
       u.legacy_user_id AS username,
       u.display_name AS name,
       COALESCE(NULLIF(u.label, ''), u.display_name) AS label,
       u.color,
       COALESCE((SELECT m.role FROM identity.memberships m
                 WHERE m.organization_id=u.organization_id AND m.user_id=u.id), 'member') AS role,
       CASE WHEN u.status='active' THEN 1 ELSE 0 END AS active,
       u.created_at::text AS created_at,
       ''::text AS password_hash,
       ''::text AS created_by
FROM identity.users u
WHERE u.organization_id = '859a998d-1b48-589b-8035-34dc65c01440'::uuid;

CREATE OR REPLACE VIEW trosa.customers AS
SELECT r.legacy_customer_id AS id,
       a.display_name AS name,
       c.canonical_name AS company,
       c.country_code AS country,
       a.priority_level AS level,
       a.channel_type AS type,
       c.website,
       a.profile,
       a.field,
       a.account_status AS status,
       COALESCE(a.legacy_payload->>'notes', '') AS notes,
       COALESCE(a.legacy_payload->>'system_notes', '') AS system_notes,
       COALESCE(a.last_contact_at::text, a.legacy_payload->>'last_contact', '') AS last_contact,
       COALESCE(a.next_follow_up_at::text, a.legacy_payload->>'next_follow_up', '') AS next_follow_up,
       CASE WHEN lower(COALESCE(a.legacy_payload->>'manual_next_follow','0')) IN ('1','true') THEN 1 ELSE 0 END AS manual_next_follow,
       a.customer_type,
       a.industry,
       a.company_size,
       a.annual_revenue,
       a.tags,
       COALESCE(a.legacy_payload->>'import_source', 'legacy') AS import_source,
       COALESCE(a.legacy_payload->>'external_source', '') AS external_source,
       COALESCE(a.legacy_payload->>'external_id', '') AS external_id,
       a.attention_state,
       a.attention_reason,
       COALESCE(a.attention_updated_at::text, a.legacy_payload->>'attention_updated_at', '') AS attention_updated_at,
       COALESCE(a.attention_review_date::text, a.legacy_payload->>'attention_review_date', '') AS attention_review_date,
       CASE WHEN a.is_pinned THEN 1 ELSE 0 END AS is_pinned,
       a.pinned_order,
       COALESCE(a.legacy_payload->>'pinned_at', '') AS pinned_at,
       CASE WHEN a.deleted_at IS NULL THEN 0 ELSE 1 END AS is_deleted,
       COALESCE(a.deleted_at::text, '') AS deleted_at,
       a.created_at::text AS created_at,
       a.updated_at::text AS updated_at
FROM trosa.account_legacy_refs r
JOIN trosa.accounts a ON a.id=r.account_id
JOIN core.companies c ON c.id=a.company_id
WHERE r.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid
  AND r.legacy_user_id=trosa.compat_current_user();

CREATE OR REPLACE VIEW trosa.contacts AS
SELECT r.legacy_contact_id AS id,
       r.legacy_customer_id AS customer_id,
       COALESCE(NULLIF(r.name, ''), p.full_name, '') AS name,
       r.title,
       COALESCE(cm.value, '') AS email,
       r.phone,
       r.whatsapp,
       r.linkedin,
       r.preferred_channel,
       r.contact_type,
       CASE WHEN r.is_primary THEN 1 ELSE 0 END AS is_primary,
       r.notes,
       r.created_at::text AS created_at
FROM trosa.contact_legacy_refs r
LEFT JOIN core.people p ON p.id=r.person_id
LEFT JOIN core.contact_methods cm ON cm.id=r.contact_method_id
WHERE r.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid
  AND r.legacy_user_id=trosa.compat_current_user();

CREATE OR REPLACE VIEW trosa.reminders AS
SELECT lr.legacy_id AS id,
       ar.legacy_customer_id AS customer_id,
       t.title,
       t.content,
       t.reason,
       t.due_at::text AS remind_date,
       CASE WHEN t.status='done' THEN 1 ELSE 0 END AS is_done,
       t.task_type AS reminder_type,
       COALESCE(t.completed_at::text, '') AS completed_at,
       NULLIF(t.source_activity_legacy_id, '')::bigint AS source_activity_id,
       t.manual_order,
       t.created_at::text AS created_at,
       t.updated_at::text AS updated_at
FROM trosa.legacy_row_refs lr
JOIN trosa.tasks t ON t.id=lr.target_id
JOIN trosa.account_legacy_refs ar ON ar.account_id=t.account_id
 AND ar.organization_id=lr.organization_id AND ar.legacy_user_id=lr.legacy_user_id
WHERE lr.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid
  AND lr.legacy_user_id=trosa.compat_current_user() AND lr.table_name='reminders';

CREATE OR REPLACE VIEW trosa.follow_up_logs AS
SELECT lr.legacy_id AS id,
       ar.legacy_customer_id AS customer_id,
       e.content,
       e.occurred_at::text AS follow_date,
       e.result,
       e.next_plan,
       e.event_type AS activity_type,
       e.direction,
       NULL::bigint AS contact_id,
       NULL::bigint AS related_task_id,
       e.source_module AS source,
       CASE WHEN lower(COALESCE(e.payload->>'is_reported','0')) IN ('1','true') THEN 1 ELSE 0 END AS is_reported,
       CASE WHEN lower(COALESCE(e.payload->>'is_deleted','0')) IN ('1','true') THEN 1 ELSE 0 END AS is_deleted,
       COALESCE(e.payload->>'deleted_at', '') AS deleted_at,
       e.created_at::text AS updated_at,
       e.created_at::text AS created_at
FROM trosa.legacy_row_refs lr
JOIN trosa.timeline_events e ON e.id=lr.target_id
JOIN trosa.account_legacy_refs ar ON ar.account_id=e.account_id
 AND ar.organization_id=lr.organization_id AND ar.legacy_user_id=lr.legacy_user_id
WHERE lr.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid
  AND lr.legacy_user_id=trosa.compat_current_user() AND lr.table_name='follow_up_logs';

CREATE OR REPLACE VIEW trosa.outreach_emails AS
SELECT lr.legacy_id AS id,
       ar.legacy_customer_id AS customer_id,
       o.subject,
       o.body AS content,
       COALESCE(o.sent_at::text, '') AS sent_date,
       o.reply_status,
       o.reply_content,
       COALESCE(o.reply_at::text, '') AS reply_date,
       CASE WHEN lower(COALESCE(o.legacy_payload->>'is_reported','0')) IN ('1','true') THEN 1 ELSE 0 END AS is_reported,
       o.created_at::text AS created_at,
       COALESCE(o.legacy_payload->>'external_source', '') AS external_source,
       COALESCE(o.provider_message_id, o.legacy_payload->>'external_id', '') AS external_id,
       COALESCE(o.legacy_payload->>'external_updated_at', '') AS external_updated_at,
       COALESCE(o.legacy_payload->>'recipient_email', '') AS recipient_email,
       NULL::bigint AS contact_id,
       COALESCE(o.legacy_payload->>'message_id', o.provider_message_id, '') AS message_id
FROM trosa.legacy_row_refs lr
JOIN trosa.outreach_messages o ON o.id=lr.target_id
JOIN trosa.account_legacy_refs ar ON ar.account_id=o.account_id
 AND ar.organization_id=lr.organization_id AND ar.legacy_user_id=lr.legacy_user_id
WHERE lr.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid
  AND lr.legacy_user_id=trosa.compat_current_user() AND lr.table_name='outreach_emails';

CREATE OR REPLACE FUNCTION trosa.compat_customers_write() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    legacy_user text := trosa.compat_current_user();
    legacy_customer_id bigint;
    company_id uuid;
    account_id uuid;
    company_name text;
    normalized_name text;
    country text;
    website text;
    dom text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        UPDATE trosa.accounts
           SET deleted_at=now(),updated_at=now()
         WHERE id=(SELECT ar.account_id FROM trosa.account_legacy_refs ar
                   WHERE ar.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid
                     AND ar.legacy_user_id=legacy_user AND ar.legacy_customer_id=OLD.id);
        RETURN OLD;
    END IF;

    legacy_customer_id := CASE WHEN TG_OP='INSERT' AND (NEW.id IS NULL OR NEW.id=0)
        THEN (SELECT coalesce(max(ar.legacy_customer_id),0)+1 FROM trosa.account_legacy_refs ar
              WHERE ar.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND ar.legacy_user_id=legacy_user)
        ELSE NEW.id END;
    company_name := coalesce(nullif(trim(NEW.company),''), nullif(trim(NEW.name),''), 'UNKNOWN');
    normalized_name := trosa.compat_normalized_name(company_name);
    country := coalesce(NEW.country,'');
    website := coalesce(NEW.website,'');
    dom := trosa.compat_domain(website);

    IF dom <> '' THEN
        SELECT d.company_id INTO company_id FROM core.company_domains d
         WHERE d.normalized_domain=dom LIMIT 1;
    ELSE
        SELECT c.id INTO company_id FROM core.companies c
         WHERE c.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid
           AND c.normalized_name=normalized_name AND c.country_code=country LIMIT 1;
    END IF;
    IF company_id IS NULL THEN
        company_id := trosa.compat_uuid(CASE WHEN dom<>'' THEN 'company:domain:'||dom
                                             ELSE 'company:name:'||normalized_name||'|'||trosa.compat_normalized_name(country) END);
        INSERT INTO core.companies(id,organization_id,canonical_name,normalized_name,website,country_code)
        VALUES (company_id,'859a998d-1b48-589b-8035-34dc65c01440'::uuid,company_name,normalized_name,website,country)
        ON CONFLICT (id) DO UPDATE SET canonical_name=excluded.canonical_name,
          normalized_name=excluded.normalized_name,website=excluded.website,country_code=excluded.country_code,updated_at=now();
    ELSE
        UPDATE core.companies SET canonical_name=company_name,website=website,country_code=country,updated_at=now()
         WHERE id=company_id AND (TG_OP='INSERT' OR coalesce(NEW.company,'')<>'');
    END IF;
    IF dom<>'' THEN
        INSERT INTO core.company_domains(id,company_id,normalized_domain,source_url,is_primary,verification_status)
        VALUES (trosa.compat_uuid('company-domain:'||dom),company_id,dom,website,true,'imported')
        ON CONFLICT (company_id,normalized_domain) DO UPDATE SET source_url=excluded.source_url;
    END IF;
    account_id := trosa.compat_uuid('account:'||company_id::text);
    INSERT INTO trosa.accounts(id,organization_id,company_id,display_name,account_status,customer_type,channel_type,priority_level,profile,field,industry,company_size,annual_revenue,tags,attention_state,attention_reason,last_contact_at,next_follow_up_at,deleted_at,legacy_payload,updated_at)
    VALUES (account_id,'859a998d-1b48-589b-8035-34dc65c01440'::uuid,company_id,coalesce(NEW.name,''),coalesce(NEW.status,''),coalesce(NEW.customer_type,'existing'),coalesce(NEW.type,''),coalesce(NEW.level,'C'),coalesce(NEW.profile,''),coalesce(NEW.field,''),coalesce(NEW.industry,''),coalesce(NEW.company_size,''),coalesce(NEW.annual_revenue,''),coalesce(NEW.tags,''),coalesce(NEW.attention_state,''),coalesce(NEW.attention_reason,''),NULLIF(NEW.last_contact,'')::timestamptz,NULLIF(NEW.next_follow_up,'')::timestamptz,CASE WHEN coalesce(NEW.is_deleted,0)=1 THEN now() ELSE NULL END,coalesce(to_jsonb(NEW),'{}'::jsonb),now())
    ON CONFLICT (organization_id,company_id) DO UPDATE SET display_name=excluded.display_name,account_status=excluded.account_status,customer_type=excluded.customer_type,channel_type=excluded.channel_type,priority_level=excluded.priority_level,profile=excluded.profile,field=excluded.field,industry=excluded.industry,company_size=excluded.company_size,annual_revenue=excluded.annual_revenue,tags=excluded.tags,attention_state=excluded.attention_state,attention_reason=excluded.attention_reason,last_contact_at=excluded.last_contact_at,next_follow_up_at=excluded.next_follow_up_at,deleted_at=excluded.deleted_at,legacy_payload=trosa.accounts.legacy_payload || excluded.legacy_payload,updated_at=now();
    INSERT INTO trosa.account_legacy_refs(organization_id,legacy_user_id,legacy_customer_id,account_id,source_db)
    VALUES ('859a998d-1b48-589b-8035-34dc65c01440'::uuid,legacy_user,legacy_customer_id,account_id,legacy_user||'.db')
    ON CONFLICT (organization_id,legacy_user_id,legacy_customer_id) DO UPDATE SET account_id=excluded.account_id;
    PERFORM trosa.compat_set_lastrowid(legacy_customer_id);
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS compat_customers_write ON trosa.customers;
CREATE TRIGGER compat_customers_write
INSTEAD OF INSERT OR UPDATE OR DELETE ON trosa.customers
FOR EACH ROW EXECUTE FUNCTION trosa.compat_customers_write();

CREATE OR REPLACE FUNCTION trosa.compat_contacts_write() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    legacy_user text := trosa.compat_current_user();
    contact_id bigint;
    account_id uuid;
    company_id uuid;
    person_id uuid;
    method_id uuid;
    email_value text := lower(trim(coalesce(NEW.email,'')));
BEGIN
    IF TG_OP='DELETE' THEN
        DELETE FROM trosa.contact_legacy_refs WHERE organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND legacy_user_id=legacy_user AND legacy_contact_id=OLD.id;
        RETURN OLD;
    END IF;
    contact_id := CASE WHEN TG_OP='INSERT' AND (NEW.id IS NULL OR NEW.id=0)
        THEN (SELECT coalesce(max(cr.legacy_contact_id),0)+1 FROM trosa.contact_legacy_refs cr WHERE cr.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND cr.legacy_user_id=legacy_user)
        ELSE NEW.id END;
    SELECT r.account_id,c.company_id INTO account_id,company_id
      FROM trosa.account_legacy_refs r JOIN trosa.accounts c ON c.id=r.account_id
     WHERE r.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND r.legacy_user_id=legacy_user AND r.legacy_customer_id=NEW.customer_id LIMIT 1;
    IF account_id IS NULL THEN
        RAISE EXCEPTION 'customer % is not visible for user %',NEW.customer_id,legacy_user;
    END IF;
    IF email_value<>'' THEN person_id := trosa.compat_uuid('person:email:'||email_value); ELSE person_id := trosa.compat_uuid('person:'||legacy_user||':'||contact_id::text); END IF;
    INSERT INTO core.people(id,organization_id,full_name,normalized_name)
    VALUES (person_id,'859a998d-1b48-589b-8035-34dc65c01440'::uuid,coalesce(nullif(trim(NEW.name),''),'UNKNOWN'),trosa.compat_normalized_name(NEW.name))
    ON CONFLICT (id) DO UPDATE SET full_name=CASE WHEN core.people.full_name IN ('','UNKNOWN') THEN excluded.full_name ELSE core.people.full_name END,updated_at=now();
    INSERT INTO core.company_people(id,company_id,person_id,title,source)
    VALUES (trosa.compat_uuid('company-person:'||company_id::text||':'||person_id::text||':'||coalesce(NEW.title,'')),company_id,person_id,coalesce(NEW.title,''),'trosa')
    ON CONFLICT DO NOTHING;
    IF email_value<>'' THEN
        INSERT INTO core.contact_methods(id,organization_id,person_id,kind,value,normalized_value,evidence)
        VALUES (trosa.compat_uuid('email:'||email_value),'859a998d-1b48-589b-8035-34dc65c01440'::uuid,person_id,'email',email_value,email_value,'{}'::jsonb)
        ON CONFLICT (organization_id,kind,normalized_value) DO UPDATE SET person_id=coalesce(core.contact_methods.person_id,excluded.person_id),updated_at=now();
        SELECT id INTO method_id FROM core.contact_methods WHERE organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND kind='email' AND normalized_value=email_value;
    END IF;
    INSERT INTO trosa.contact_legacy_refs(organization_id,legacy_user_id,legacy_contact_id,legacy_customer_id,account_id,person_id,contact_method_id,name,title,phone,whatsapp,linkedin,preferred_channel,contact_type,is_primary,notes,legacy_payload,updated_at)
    VALUES ('859a998d-1b48-589b-8035-34dc65c01440'::uuid,legacy_user,contact_id,NEW.customer_id,account_id,person_id,method_id,coalesce(NEW.name,''),coalesce(NEW.title,''),coalesce(NEW.phone,''),coalesce(NEW.whatsapp,''),coalesce(NEW.linkedin,''),coalesce(NEW.preferred_channel,''),coalesce(NEW.contact_type,'person'),coalesce(NEW.is_primary,0)<>0,coalesce(NEW.notes,''),coalesce(to_jsonb(NEW),'{}'::jsonb),now())
    ON CONFLICT (organization_id,legacy_user_id,legacy_contact_id) DO UPDATE SET legacy_customer_id=excluded.legacy_customer_id,account_id=excluded.account_id,person_id=excluded.person_id,contact_method_id=excluded.contact_method_id,name=excluded.name,title=excluded.title,phone=excluded.phone,whatsapp=excluded.whatsapp,linkedin=excluded.linkedin,preferred_channel=excluded.preferred_channel,contact_type=excluded.contact_type,is_primary=excluded.is_primary,notes=excluded.notes,legacy_payload=excluded.legacy_payload,updated_at=now();
    PERFORM trosa.compat_set_lastrowid(contact_id);
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS compat_contacts_write ON trosa.contacts;
CREATE TRIGGER compat_contacts_write
INSTEAD OF INSERT OR UPDATE OR DELETE ON trosa.contacts
FOR EACH ROW EXECUTE FUNCTION trosa.compat_contacts_write();

CREATE OR REPLACE FUNCTION trosa.compat_reminders_write() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE legacy_user text := trosa.compat_current_user(); legacy_id bigint; account_id uuid; target_id uuid;
BEGIN
    IF TG_OP='DELETE' THEN
        DELETE FROM trosa.tasks WHERE id=(SELECT lr.target_id FROM trosa.legacy_row_refs lr WHERE lr.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND lr.legacy_user_id=legacy_user AND lr.table_name='reminders' AND lr.legacy_id=OLD.id);
        RETURN OLD;
    END IF;
    legacy_id := CASE WHEN TG_OP='INSERT' AND (NEW.id IS NULL OR NEW.id=0) THEN (SELECT coalesce(max(lr.legacy_id),0)+1 FROM trosa.legacy_row_refs lr WHERE lr.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND lr.legacy_user_id=legacy_user AND lr.table_name='reminders') ELSE NEW.id END;
    SELECT ar.account_id INTO account_id FROM trosa.account_legacy_refs ar WHERE ar.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND ar.legacy_user_id=legacy_user AND ar.legacy_customer_id=NEW.customer_id;
    IF account_id IS NULL THEN RAISE EXCEPTION 'customer % is not visible for user %',NEW.customer_id,legacy_user; END IF;
    target_id := trosa.compat_uuid('task:'||legacy_user||':'||legacy_id::text);
    INSERT INTO trosa.tasks(id,account_id,title,content,reason,due_at,status,task_type,source_activity_legacy_id,manual_order,completed_at,legacy_payload,updated_at)
    VALUES (target_id,account_id,coalesce(NEW.title,''),coalesce(NEW.content,''),coalesce(NEW.reason,''),NULLIF(NEW.remind_date,'')::timestamptz,CASE WHEN coalesce(NEW.is_done,0)<>0 THEN 'done' ELSE 'open' END,coalesce(NEW.reminder_type,'follow_up'),coalesce(NEW.source_activity_id::text,''),coalesce(NEW.manual_order,0),NULLIF(NEW.completed_at,'')::timestamptz,coalesce(to_jsonb(NEW),'{}'::jsonb),now())
    ON CONFLICT (id) DO UPDATE SET title=excluded.title,content=excluded.content,reason=excluded.reason,due_at=excluded.due_at,status=excluded.status,task_type=excluded.task_type,source_activity_legacy_id=excluded.source_activity_legacy_id,manual_order=excluded.manual_order,completed_at=excluded.completed_at,legacy_payload=trosa.tasks.legacy_payload||excluded.legacy_payload,updated_at=now();
    INSERT INTO trosa.legacy_row_refs(organization_id,legacy_user_id,table_name,legacy_id,target_id) VALUES ('859a998d-1b48-589b-8035-34dc65c01440'::uuid,legacy_user,'reminders',legacy_id,target_id) ON CONFLICT (organization_id,legacy_user_id,table_name,legacy_id) DO UPDATE SET target_id=excluded.target_id;
    PERFORM trosa.compat_set_lastrowid(legacy_id);
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS compat_reminders_write ON trosa.reminders;
CREATE TRIGGER compat_reminders_write INSTEAD OF INSERT OR UPDATE OR DELETE ON trosa.reminders FOR EACH ROW EXECUTE FUNCTION trosa.compat_reminders_write();

CREATE OR REPLACE FUNCTION trosa.compat_follow_up_write() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE legacy_user text := trosa.compat_current_user(); legacy_id bigint; account_id uuid; target_id uuid;
BEGIN
    IF TG_OP='DELETE' THEN DELETE FROM trosa.timeline_events WHERE id=(SELECT lr.target_id FROM trosa.legacy_row_refs lr WHERE lr.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND lr.legacy_user_id=legacy_user AND lr.table_name='follow_up_logs' AND lr.legacy_id=OLD.id); RETURN OLD; END IF;
    legacy_id := CASE WHEN TG_OP='INSERT' AND (NEW.id IS NULL OR NEW.id=0) THEN (SELECT coalesce(max(lr.legacy_id),0)+1 FROM trosa.legacy_row_refs lr WHERE lr.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND lr.legacy_user_id=legacy_user AND lr.table_name='follow_up_logs') ELSE NEW.id END;
    SELECT ar.account_id INTO account_id FROM trosa.account_legacy_refs ar WHERE ar.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND ar.legacy_user_id=legacy_user AND ar.legacy_customer_id=NEW.customer_id;
    IF account_id IS NULL THEN RAISE EXCEPTION 'customer % is not visible for user %',NEW.customer_id,legacy_user; END IF;
    target_id := trosa.compat_uuid('timeline:'||legacy_user||':'||legacy_id::text);
    INSERT INTO trosa.timeline_events(id,account_id,event_type,direction,content,result,next_plan,source_module,source_reference,occurred_at,payload)
    VALUES (target_id,account_id,coalesce(NEW.activity_type,'follow_up'),coalesce(NEW.direction,'unknown'),coalesce(NEW.content,''),coalesce(NEW.result,''),coalesce(NEW.next_plan,''),'trosa',legacy_user||':'||legacy_id::text,NULLIF(NEW.follow_date,'')::timestamptz,coalesce(to_jsonb(NEW),'{}'::jsonb))
    ON CONFLICT (id) DO UPDATE SET event_type=excluded.event_type,direction=excluded.direction,content=excluded.content,result=excluded.result,next_plan=excluded.next_plan,occurred_at=excluded.occurred_at,payload=trosa.timeline_events.payload||excluded.payload;
    INSERT INTO trosa.legacy_row_refs(organization_id,legacy_user_id,table_name,legacy_id,target_id) VALUES ('859a998d-1b48-589b-8035-34dc65c01440'::uuid,legacy_user,'follow_up_logs',legacy_id,target_id) ON CONFLICT (organization_id,legacy_user_id,table_name,legacy_id) DO UPDATE SET target_id=excluded.target_id;
    PERFORM trosa.compat_set_lastrowid(legacy_id);
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS compat_follow_up_write ON trosa.follow_up_logs;
CREATE TRIGGER compat_follow_up_write INSTEAD OF INSERT OR UPDATE OR DELETE ON trosa.follow_up_logs FOR EACH ROW EXECUTE FUNCTION trosa.compat_follow_up_write();

CREATE OR REPLACE FUNCTION trosa.compat_outreach_write() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE legacy_user text := trosa.compat_current_user(); legacy_id bigint; account_id uuid; target_id uuid;
BEGIN
    IF TG_OP='DELETE' THEN DELETE FROM trosa.outreach_messages WHERE id=(SELECT lr.target_id FROM trosa.legacy_row_refs lr WHERE lr.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND lr.legacy_user_id=legacy_user AND lr.table_name='outreach_emails' AND lr.legacy_id=OLD.id); RETURN OLD; END IF;
    legacy_id := CASE WHEN TG_OP='INSERT' AND (NEW.id IS NULL OR NEW.id=0) THEN (SELECT coalesce(max(lr.legacy_id),0)+1 FROM trosa.legacy_row_refs lr WHERE lr.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND lr.legacy_user_id=legacy_user AND lr.table_name='outreach_emails') ELSE NEW.id END;
    SELECT ar.account_id INTO account_id FROM trosa.account_legacy_refs ar WHERE ar.organization_id='859a998d-1b48-589b-8035-34dc65c01440'::uuid AND ar.legacy_user_id=legacy_user AND ar.legacy_customer_id=NEW.customer_id;
    IF account_id IS NULL THEN RAISE EXCEPTION 'customer % is not visible for user %',NEW.customer_id,legacy_user; END IF;
    target_id := trosa.compat_uuid('trosa-message:'||legacy_user||':'||legacy_id::text);
    INSERT INTO trosa.outreach_messages(id,account_id,subject,body,sent_at,reply_status,reply_content,reply_at,provider,provider_message_id,legacy_payload)
    VALUES (target_id,account_id,coalesce(NEW.subject,''),coalesce(NEW.content,''),NULLIF(NEW.sent_date,'')::timestamptz,coalesce(NEW.reply_status,'pending'),coalesce(NEW.reply_content,''),NULLIF(NEW.reply_date,'')::timestamptz,'legacy',coalesce(nullif(NEW.message_id,''),nullif(NEW.external_id,'')),coalesce(to_jsonb(NEW),'{}'::jsonb))
    ON CONFLICT (id) DO UPDATE SET subject=excluded.subject,body=excluded.body,sent_at=excluded.sent_at,reply_status=excluded.reply_status,reply_content=excluded.reply_content,reply_at=excluded.reply_at,provider_message_id=excluded.provider_message_id,legacy_payload=trosa.outreach_messages.legacy_payload||excluded.legacy_payload;
    INSERT INTO trosa.legacy_row_refs(organization_id,legacy_user_id,table_name,legacy_id,target_id) VALUES ('859a998d-1b48-589b-8035-34dc65c01440'::uuid,legacy_user,'outreach_emails',legacy_id,target_id) ON CONFLICT (organization_id,legacy_user_id,table_name,legacy_id) DO UPDATE SET target_id=excluded.target_id;
    PERFORM trosa.compat_set_lastrowid(legacy_id);
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS compat_outreach_write ON trosa.outreach_emails;
CREATE TRIGGER compat_outreach_write INSTEAD OF INSERT OR UPDATE OR DELETE ON trosa.outreach_emails FOR EACH ROW EXECUTE FUNCTION trosa.compat_outreach_write();

COMMIT;
