-- The durable, CRM-owned hand-off for autonomous prospecting agents.
--
-- It intentionally does not mirror accounts, contacts, outreach, delivery,
-- replies or tasks. Those facts already have canonical Trosa tables. This
-- relation only binds an agent's stable source identity to a customer and
-- holds its research/transport metadata and explicit contact suppression.

BEGIN;

CREATE TABLE IF NOT EXISTS trosa.agent_prospect_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id uuid NOT NULL DEFAULT trosa.compat_org_id()
        REFERENCES identity.organizations(id),
    legacy_user_id text NOT NULL DEFAULT trosa.compat_current_user(),
    source text NOT NULL DEFAULT 'sela',
    source_id text NOT NULL,
    customer_id bigint NOT NULL,
    research_json text NOT NULL DEFAULT '{}',
    contact_permission text NOT NULL DEFAULT 'allowed'
        CHECK(contact_permission IN ('allowed', 'do_not_contact')),
    suppression_reason text NOT NULL DEFAULT '',
    suppression_at text NOT NULL DEFAULT '',
    transport_json text NOT NULL DEFAULT '{}',
    created_at text NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at text NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (organization_id, legacy_user_id, source, source_id),
    UNIQUE (organization_id, legacy_user_id, source, customer_id)
);

CREATE INDEX IF NOT EXISTS trosa_agent_prospect_profiles_customer_idx
    ON trosa.agent_prospect_profiles
       (organization_id, legacy_user_id, customer_id, updated_at DESC);

COMMIT;
