-- CRM-owned business exclusion records.
--
-- Some historical exclusions identify a company only by name or domain and
-- therefore cannot honestly be forced into an account row.  This narrow,
-- generic relation keeps that safety fact in Trosa instead of a specific
-- agent's files.  ``source``/``source_id`` make one-way legacy imports
-- repeatable without treating those identifiers as a second CRM identity.

BEGIN;

CREATE TABLE IF NOT EXISTS trosa.business_exclusions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id uuid NOT NULL DEFAULT trosa.compat_org_id()
        REFERENCES identity.organizations(id),
    legacy_user_id text NOT NULL DEFAULT trosa.compat_current_user(),
    source text NOT NULL,
    source_id text NOT NULL,
    canonical_name text NOT NULL,
    normalized_name text NOT NULL DEFAULT '',
    aliases_json text NOT NULL DEFAULT '[]',
    domains_json text NOT NULL DEFAULT '[]',
    country text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'confirmed_exclude',
    match_policy text NOT NULL DEFAULT 'hard'
        CHECK(match_policy IN ('hard', 'review_name_only')),
    reason text NOT NULL DEFAULT '',
    linked_customer_id bigint,
    is_active integer NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1)),
    created_at text NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at text NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (organization_id, legacy_user_id, source, source_id)
);

CREATE INDEX IF NOT EXISTS trosa_business_exclusions_active_idx
    ON trosa.business_exclusions
       (organization_id, legacy_user_id, is_active, updated_at DESC);

COMMIT;
